# This file is generated by androgenizer for:
# [x] NDK
# [ ] system
LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)
LOCAL_C_INCLUDES := ../json-c
LOCAL_LDLIBS :=-L../json-c/libs/armeabi -ljson-c
LOCAL_MODULE:=json-cTest

LOCAL_MODULE_TAGS:=eng debug 

LOCAL_SRC_FILES := \
	jsonTest.c
LOCAL_PRELINK_MODULE := false


LOCAL_ARM_MODE:=arm

include $(BUILD_EXECUTABLE)
